[build]
  command = "cd nextjs-app && npm install && npm run build"
  publish = "nextjs-app/.next"

# Configure secrets scanning to ignore expected environment variables
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,ADMIN_EMAIL"